## 파일확장자 SAV (SPSS 통계용 파일) 불러오기

In [1]:
!pip install pyreadstat

Collecting pyreadstat
  Downloading pyreadstat-1.1.5-cp37-cp37m-win_amd64.whl (1.3 MB)
Requirement already satisfied: pandas>=1.2.0 in c:\users\ygl\anaconda3\lib\site-packages (from pyreadstat) (1.3.4)
Requirement already satisfied: numpy>=1.17.3 in c:\users\ygl\anaconda3\lib\site-packages (from pandas>=1.2.0->pyreadstat) (1.21.5)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\ygl\anaconda3\lib\site-packages (from pandas>=1.2.0->pyreadstat) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in c:\users\ygl\anaconda3\lib\site-packages (from pandas>=1.2.0->pyreadstat) (2021.3)
Requirement already satisfied: six>=1.5 in c:\users\ygl\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas>=1.2.0->pyreadstat) (1.16.0)
Installing collected packages: pyreadstat
Successfully installed pyreadstat-1.1.5

In [2]:
import pandas as pd

In [3]:
data1=pd.read_spss("klowf_08_p.SAV")
data1.head()

,OPID,Pwave,PwaveA,PwaveB,PDAY,PweiL,PweiC,PweiCA,H01HHID,H02HHID,...,H06BI01,H06BI02,H06BI03,H06LE01,H06SA01,H06SA02,H06SA03,H06SA04A,H06SA04B,H06SA04C
0,101.0,8차,기존 응답,8차 기존 응답자,2021-01-27,21546.152959,20672.523389,10993.406063,1.0,1.0,...,감소했다,해당사항 없음,해당사항 없음,동일하다,30.0,0.0,본인,식비(주식비와 부식비),"보건의료비(병원 및 약국 등에 지출한 진찰비 및 의료비 등 포함, 단, 의료보험료 제외)",NaN
1,402.0,8차,기존 응답,8차 기존 응답자,2021-01-30,1178.487565,1205.231058,611.743683,4.0,4.0,...,동일하다,동일하다,동일하다,증가했다,120.0,0.0,본인,식비(주식비와 부식비),외식비,NaN
2,502.0,8차,기존 응답,8차 기존 응답자,2021-01-30,4834.557136,4316.123446,2295.263949,5.0,5.0,...,동일하다,증가했다,동일하다,감소했다,80.0,80.0,본인,모르겠음,NaN,NaN
3,503.0,8차,신규 응답,8차 신규 응답자,2021-02-07,0.000000,4181.845925,1471.793040,NaN,NaN,...,동일하다,해당사항 없음,해당사항 없음,증가했다,30.0,0.0,본인,외식비,"피복신발비(의류, 신발 등의 구입, 수선, 세탁, 대여료)",NaN
4,901.0,8차,기존 응답,8차 기존 응답자,2021-03-22,5379.459537,5081.984438,2448.998071,9.0,9.0,...,감소했다,해당사항 없음,해당사항 없음,감소했다,40.0,0.0,본인,식비(주식비와 부식비),외식비,NaN

## 선택한 변수만 가지고 오기

In [4]:
target1=data1[["Pwave","PwaveB","H05FC","H05LE12","H05LE13"]]
target1.head()

  Pwave     PwaveB       H05FC         H05LE12   H05LE13
0    8차  8차 기존 응답자  조금 어려운 편이다             의료비  식비(식료품비)
1    8차  8차 기존 응답자        보통이다  주거비(관리비, 월세 등)  식비(식료품비)
2    8차  8차 기존 응답자  여유가 있는 편이다              없음       NaN
3    8차  8차 신규 응답자        보통이다          교통/통신비       보험료
4    8차  8차 기존 응답자  조금 어려운 편이다  주거비(관리비, 월세 등)  식비(식료품비)

## 선택한 변수로 이루어진 데이터프레임의 변수를 한글로 알아보기 쉽게 변경하기

In [5]:
target1.columns=["차수","기존여부","살림살이","1차비용","2차비용"]
target1.head()

   차수       기존여부        살림살이            1차비용      2차비용
0  8차  8차 기존 응답자  조금 어려운 편이다             의료비  식비(식료품비)
1  8차  8차 기존 응답자        보통이다  주거비(관리비, 월세 등)  식비(식료품비)
2  8차  8차 기존 응답자  여유가 있는 편이다              없음       NaN
3  8차  8차 신규 응답자        보통이다          교통/통신비       보험료
4  8차  8차 기존 응답자  조금 어려운 편이다  주거비(관리비, 월세 등)  식비(식료품비)

###  csv  파일 형태로 지정된 폴더에 저장해보기

In [7]:
target1.to_csv("target2.csv",index=False)

파일을 열어서 원하는 형태가 되었는지 확인해봅시다

E.O.D